# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def common_pods!
    
end


target 'BOILER_PLATE_TEMPLATE-iOS' do
    #use_frameworks!
    common_pods!
    
    target 'BOILER_PLATE_TEMPLATE-iOSTests' do
        common_pods!
    end
    
end

target 'BOILER_PLATE_TEMPLATE-macOS' do
    #use_frameworks!
    
    common_pods!
    target 'BOILER_PLATE_TEMPLATE-macOSTests' do
       common_pods!
    end
    
end

target 'BOILER_PLATE_TEMPLATE-tvOS' do
    #use_frameworks!
    
    common_pods!
    
    target 'BOILER_PLATE_TEMPLATE-tvOSTests' do
        common_pods!
    end
    
end
